version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 80:80
  fluentd:
    build:
      context: .
      dockerfile: docker/Dockerfile.fluentd
    ports:
      - 9191:9191
    environment:
      - DD_API_KEY
