version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./nginx/conf.d/:/etc/nginx/conf.d/:cached
    links:
      - fluentd
    ports:
      - 80:80
  fluentd:
    build: .
    volumes:
      - ./fluent/fluent.conf:/fluentd/etc/fluent.conf:cached
      - ./fluent/:/fluentd/log:cached
    # command: "fluentd -vv -o /fluentd/log/trace.log"
    ports:
      - 9191:9191
    environment:
      - DD_API_KEY
